title: PackageManager
show_downloads: false
google_analytics:

repository: distriqt/ANE-PackageManager
exclude: ["_Sidebar.md, _Footer.md"]
theme: jekyll-theme-minimal

gems: 
  - jekyll-redirect-from

